function [r] = permutationProbabilityRatio(p, theta, A, u, v)
% PERMUTATIONPROBABILITYRATIO
%   This function evaluates equations 5.7 and 5.8 in the thesis to
%   determine if the likelihood of the adjacency matrix being generated by
%   A will increase or decrease when the labeling of As nodes is evaluated
%   with permutations p and p with the terms u and v swapped.
%
% Auth: Joshua Pickard
%       jpic@umich.edu
% Date: June 5, 2023

n = size(A,1);
% n0 = size(theta,1);
% k = log(n) / log(n0);

p1 = p;                         % permutation 1
p2 = p; p2([u v]) = p2([v u]);  % permutation 2

r = 1;
for i=1:n
    % if i == v; continue; end
    e1 = edgeProbability(n, theta, p1(u), p1(i));
    e2 = edgeProbability(n, theta, p2(u), p2(i));
    if A(u,i) == 1
        rij = e1 / e2;
    else
        rij = (1 - e1) / (1 - e2);
    end
    r = r * (rij);
end
for i=1:n
    % if i == v; continue; end
    e1 = edgeProbability(n, theta, p1(v), p1(i));
    e2 = edgeProbability(n, theta, p2(v), p2(i));
    if A(u,i) == 1
        rij = e1 / e2;
    else
        rij = (1 - e1) / (1 - e2);
    end
    r = r * (rij);
end

end

%{
for i=1:n
    if i == u; continue; end
    e1 = edgeProbability(n, theta, p1(v), p1(i));
    e2 = edgeProbability(n, theta, p2(v), p2(i));
    if A(v,i) == 1
        rij = e1 / e2;
    else
        rij = (1 - e1) / (1 - e2);
    end
    r = r * rij;
end
%}

%{
    for i=1:n
        for j=1:n
            e1 = edgeProbability(n, theta, p1(i), p1(j));
            e2 = edgeProbability(n, theta, p2(i), p2(j));
            if A(i,j) == 1
                rij = e1 / e2;
            else
                rij = (1 - e1) / (1 - e2);
            end
            r = r * rij;
        end
    end
%}